### PR TITLE
Minor code quality

### PR DESCRIPTION
**Pull request by NyorJa**
* Use Lombok to avoid boilerplate code in model
   * Use ExceptionHandler in controller
   * Specify exception

If your good with this changes then I will do it to rest of methods in Stock. I am not sure if your good with lombok. I did not manage to this in actual I am relying only on the unit test.

### CODE REVIEW

**Comment by Sarthakdtu** [comment]
Hey @NyorJa, 

Thanks for the suggestion, but I would prefer to write the boiler plate code myself. 
I am learning java and spring boot, so that's why I would like to stick with the manual work as much as possible.

As for the exception, I am handling them on the go using try catch and logging them, so that server won't halt.
I like idea of having our own exceptions, but I would prefer to put that on hold as when actual exceptions are thrown, I get more information. 

But surely will add custom exception when the whole logic part is completed.

For logging, I have made a class called LoggerService in helpers package. I would prefer if you could log using that and please let me know if the `@Slf4j` is better than my solution. I genuinely want to understand the difference between these two.

My target here is not to write less code and build a working application but to understand reason behind each and every line, annotation or error.
We can definitely make it better as soon as we have a working application.

Hope this makes sense. Let me know if I missed anything.

Best Regards 
Sarthak

**Comment by Sarthakdtu** [comment]
Also, if you want to test APIs, I can share postman collections with you.
Let me know how can I do that...

**Comment by NyorJa** [comment]
Ok..noted on that..Please guide me on the next steps

**Comment by Sarthakdtu** [comment]
I would suggest to understand my sell logic, you can check the PR of sell logic.
If you have any suggestions on improving that, that would be great.

Or if you want, you can write the buy logic yourself as I have completed sell logic.
Just don't push all the commits at once. It is difficult to review so many changes at once.
You can create a branch named 'buy-logic-nyorja" and push changes one by one.
After one commit you can make a PR and I would be able to see the changes made on that commit. 
After reviewing the commit, I will comment on it and you can go ahead and keep on adding code for that.

Let me know if this works. Open to suggestions!!!

Or if you want to contribute on something else, like interceptor, front-end, you are most welcome.
I am not good with front-end, so if you have any experience in that domain, that would be great.

**Comment by Sarthakdtu** [comment]
Also, if you are good with python, you can contribute to one of y other repository https://github.com/Sarthakdtu/ByteNet
There are a lot of open issues.
Totally up-to you!!

**Pull request closed without merging**
